package vn.com.telsoft.entity;
// Generated Jan 25, 2014 4:35:06 PM by Hibernate Tools 3.6.0

/**
 * DistributorRef generated by hbm2java
 */
public class SMSCommand implements java.io.Serializable {

    private static final long serialVersionUID = -1149217365581498291L;

    private long cmdId;
    private String cmdCode;
    private String cmdType;
    private String cmdMsgContent;
    private long cmdParamCount;
    private String description;
    private String cmdRegex;
    private String status;


    public SMSCommand() {
    }

    public SMSCommand(SMSCommand ett) {
        this.cmdId = ett.getCmdId();
        this.cmdCode = ett.getCmdCode();
        this.cmdType = ett.getCmdType();
        this.cmdMsgContent = ett.getCmdMsgContent();
        this.cmdParamCount = ett.getCmdParamCount();
        this.description = ett.getDescription();
        this.cmdRegex = ett.getCmdRegex();
        this.status = ett.getStatus();
    }

    public long getCmdId() {
        return cmdId;
    }

    public void setCmdId(long cmdId) {
        this.cmdId = cmdId;
    }

    public String getCmdCode() {
        return cmdCode;
    }

    public void setCmdCode(String cmdCode) {
        this.cmdCode = cmdCode;
    }

    public String getCmdType() {
        return cmdType;
    }

    public void setCmdType(String cmdType) {
        this.cmdType = cmdType;
    }

    public String getCmdMsgContent() {
        return cmdMsgContent;
    }

    public void setCmdMsgContent(String cmdMsgContent) {
        this.cmdMsgContent = cmdMsgContent;
    }

    public long getCmdParamCount() {
        return cmdParamCount;
    }

    public void setCmdParamCount(long cmdParamCount) {
        this.cmdParamCount = cmdParamCount;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getCmdRegex() {
        return cmdRegex;
    }

    public void setCmdRegex(String cmdRegex) {
        this.cmdRegex = cmdRegex;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }
}
